FROM registry.access.redhat.com/ubi9/ubi

RUN export ARCH="$(uname -m)" && \
    yum install -y git make gcc-toolset-12 python3.12-pip python3.12 python3.12-devel java-11-openjdk unzip git-lfs && \
    export PATH="/opt/rh/gcc-toolset-12/root/usr/bin:${PATH}" && \
    export GCC_HOME="/opt/rh/gcc-toolset-12/root/usr" && \
    export JAVA_HOME="/usr/lib/jvm/java-11-openjdk-11.0.25.0.9-2.el9.ppc64le" && \
    echo "PATH="${PATH}"" >> ${HOME}/.profile && \
    echo "PATH="${PATH}"" >> ${HOME}/.bashrc && \
    echo "GCC_HOME="${GCC_HOME}"" >> ${HOME}/.bashrc && \
    echo "JAVA_HOME="${JAVA_HOME}"" >> ${HOME}/.bashrc && \
    git config --global http.version HTTP/1.1 && \
    git config --global http.postBuffer 157286400
